name: benchcoe
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _sysroot_linux-64_curr_repodata_hack=3=haa98f57_10
  - aiohttp=3.9.5=py311h5eee18b_0
  - aiosignal=1.2.0=pyhd3eb1b0_0
  - arrow-cpp=16.1.0=hc1eb8f0_0
  - attrs=23.1.0=py311h06a4308_0
  - aws-c-auth=0.6.19=h5eee18b_0
  - aws-c-cal=0.5.20=hdbd6064_0
  - aws-c-common=0.8.5=h5eee18b_0
  - aws-c-compression=0.2.16=h5eee18b_0
  - aws-c-event-stream=0.2.15=h6a678d5_0
  - aws-c-http=0.6.25=h5eee18b_0
  - aws-c-io=0.13.10=h5eee18b_0
  - aws-c-mqtt=0.7.13=h5eee18b_0
  - aws-c-s3=0.1.51=hdbd6064_0
  - aws-c-sdkutils=0.1.6=h5eee18b_0
  - aws-checksums=0.1.13=h5eee18b_0
  - aws-crt-cpp=0.18.16=h6a678d5_0
  - aws-sdk-cpp=1.10.55=h721c034_0
  - binutils=2.38=h1680402_1
  - binutils_impl_linux-64=2.38=h2a08ee3_1
  - binutils_linux-64=2.38.0=hc2dff05_0
  - blas=1.0=mkl
  - boost-cpp=1.82.0=hdb19cb5_2
  - bottleneck=1.3.7=py311hf4808d0_0
  - brotli-python=1.0.9=py311h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.7.2=h06a4308_0
  - certifi=2024.7.4=py311h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - cuda=11.8.0=0
  - cuda-cccl=12.4.127=0
  - cuda-command-line-tools=11.8.0=0
  - cuda-compiler=12.4.1=h6a678d5_1
  - cuda-cudart=11.8.89=0
  - cuda-cudart-dev=11.8.89=0
  - cuda-cuobjdump=12.4.127=0
  - cuda-cupti=11.8.87=0
  - cuda-cuxxfilt=12.4.127=0
  - cuda-demo-suite=12.4.127=0
  - cuda-documentation=12.4.127=0
  - cuda-driver-dev=12.4.127=0
  - cuda-gdb=12.4.127=0
  - cuda-libraries=11.8.0=0
  - cuda-libraries-dev=12.6.0=0
  - cuda-memcheck=11.8.86=0
  - cuda-nsight=12.4.127=0
  - cuda-nvcc=12.4.131=0
  - cuda-nvdisasm=12.4.127=0
  - cuda-nvml-dev=12.4.127=0
  - cuda-nvprof=12.4.127=0
  - cuda-nvprune=12.4.127=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvrtc-dev=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-nvvp=12.4.127=0
  - cuda-opencl=12.4.127=0
  - cuda-opencl-dev=12.4.127=0
  - cuda-profiler-api=12.4.127=0
  - cuda-runtime=11.8.0=0
  - cuda-sanitizer-api=12.4.127=0
  - cuda-toolkit=11.8.0=0
  - cuda-tools=11.8.0=0
  - cuda-visual-tools=12.6.0=0
  - cudatoolkit=11.8.0=h6a678d5_0
  - cudnn=8.9.2.26=cuda11_0
  - datasets=2.19.1=py311h06a4308_0
  - dill=0.3.8=py311h06a4308_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py311h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - frozenlist=1.4.0=py311h5eee18b_0
  - fsspec=2024.3.1=py311h06a4308_0
  - gcc_impl_linux-64=11.2.0=h1234567_1
  - gcc_linux-64=11.2.0=h5c386dc_0
  - gds-tools=1.9.1.3=0
  - gflags=2.2.2=h6a678d5_1
  - glog=0.5.0=h6a678d5_1
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py311hc9b5ff0_0
  - gnutls=3.6.15=he1e5248_0
  - gxx_impl_linux-64=11.2.0=h1234567_1
  - gxx_linux-64=11.2.0=hc2dff05_0
  - icu=73.1=h6a678d5_0
  - idna=3.7=py311h06a4308_0
  - importlib-metadata=7.0.1=py311h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.4=py311h06a4308_0
  - jpeg=9e=h5eee18b_2
  - kernel-headers_linux-64=3.10.0=h57e8cba_10
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libboost=1.82.0=h109eef0_2
  - libbrotlicommon=1.0.9=h5eee18b_8
  - libbrotlidec=1.0.9=h5eee18b_8
  - libbrotlienc=1.0.9=h5eee18b_8
  - libcublas=11.11.3.6=0
  - libcublas-dev=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufft-dev=10.9.0.58=0
  - libcufile=1.9.1.3=0
  - libcufile-dev=1.9.1.3=0
  - libcurand=10.3.5.147=0
  - libcurand-dev=10.3.5.147=0
  - libcurl=8.7.1=h251f7ec_0
  - libcusolver=11.4.1.48=0
  - libcusolver-dev=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libcusparse-dev=11.7.5.86=0
  - libdeflate=1.17=h5eee18b_1
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-devel_linux-64=11.2.0=h1234567_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libgrpc=1.62.2=h2d74bed_0
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libnpp=11.8.0.86=0
  - libnpp-dev=11.8.0.86=0
  - libnvfatbin=12.4.127=0
  - libnvfatbin-dev=12.4.127=0
  - libnvjitlink=12.4.127=0
  - libnvjitlink-dev=12.4.127=0
  - libnvjpeg=11.9.0.86=0
  - libnvjpeg-dev=11.9.0.86=0
  - libpng=1.6.39=h5eee18b_0
  - libprotobuf=4.25.3=he621ea3_0
  - libssh2=1.11.0=h251f7ec_0
  - libstdcxx-devel_linux-64=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libthrift=0.15.0=h1795dd8_2
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.3=py311h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py311h5eee18b_1
  - mkl_fft=1.3.8=py311h5eee18b_0
  - mkl_random=1.2.4=py311hdb19cb5_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py311h06a4308_0
  - multidict=6.0.4=py311h5eee18b_0
  - multiprocess=0.70.15=py311h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.3=py311h06a4308_0
  - nsight-compute=2024.1.1.4=0
  - numexpr=2.8.7=py311h65dcdc2_0
  - numpy=1.26.4=py311h08b1b3b_0
  - numpy-base=1.26.4=py311hf175353_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h9ca470c_2
  - openssl=3.0.14=h5eee18b_0
  - orc=2.0.1=h2d29ad5_0
  - packaging=24.1=py311h06a4308_0
  - pandas=2.2.2=py311ha02d727_0
  - pillow=10.4.0=py311h5eee18b_0
  - pip=24.0=py311h06a4308_0
  - pyarrow=16.1.0=py311ha02d727_0
  - pysocks=1.7.1=py311h06a4308_0
  - python=3.11.9=h955ad1f_0
  - python-dateutil=2.9.0post0=py311h06a4308_2
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python-xxhash=2.0.2=py311h5eee18b_1
  - pytorch-cuda=11.8=h7e8668a_5
  - pytorch-mutex=1.0=cuda
  - pytz=2024.1=py311h06a4308_0
  - pyyaml=6.0.1=py311h5eee18b_0
  - re2=2022.04.01=h295c915_0
  - readline=8.2=h5eee18b_0
  - regex=2023.10.3=py311h5eee18b_0
  - requests=2.32.3=py311h06a4308_0
  - s2n=1.3.27=hdbd6064_0
  - safetensors=0.4.2=py311h24d97f6_1
  - setuptools=69.5.1=py311h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.10=h6a678d5_1
  - sqlite=3.45.3=h5eee18b_0
  - sympy=1.12=py311h06a4308_0
  - sysroot_linux-64=2.17=h57e8cba_10
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - tokenizers=0.19.1=py311h585d796_0
  - torchaudio=2.0.2=py311_cu118
  - tqdm=4.66.4=py311h92b7b1e_0
  - typing-extensions=4.11.0=py311h06a4308_0
  - typing_extensions=4.11.0=py311h06a4308_0
  - tzdata=2024a=h04d1e81_0
  - urllib3=2.2.2=py311h06a4308_0
  - utf8proc=2.6.1=h5eee18b_1
  - wheel=0.43.0=py311h06a4308_0
  - xxhash=0.8.0=h7f8727e_3
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.9.3=py311h5eee18b_0
  - zipp=3.17.0=py311h06a4308_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.5=hc292b87_2
  - pip:
      - annotated-types==0.7.0
      - anyio==4.4.0
      - asttokens==2.4.1
      - backcall==0.2.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - click==8.1.7
      - cloudpickle==3.0.0
      - cmake==3.30.2
      - decorator==5.1.1
      - defusedxml==0.7.1
      - diskcache==5.6.3
      - distro==1.9.0
      - docopt==0.6.2
      - einops==0.8.0
      - executing==2.0.1
      - fastapi==0.112.0
      - fastjsonschema==2.20.0
      - h11==0.14.0
      - httpcore==1.0.5
      - httptools==0.6.1
      - httpx==0.27.0
      - huggingface-hub==0.24.5
      - interegular==0.3.3
      - ipython==8.12.3
      - jedi==0.19.1
      - jiter==0.5.0
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.2
      - jupyter-core==5.7.2
      - jupyterlab-pygments==0.3.0
      - lark==1.1.9
      - llvmlite==0.43.0
      - lm-format-enforcer==0.10.3
      - matplotlib-inline==0.1.7
      - mistune==3.0.2
      - msgpack==1.0.8
      - nbclient==0.10.0
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - ninja==1.11.1.1
      - numba==0.60.0
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-ml-py==12.555.43
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.6.20
      - nvidia-nvtx-cu12==12.1.105
      - openai==1.40.1
      - outlines==0.0.46
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pipreqs==0.5.0
      - platformdirs==4.2.2
      - prometheus-client==0.20.0
      - prometheus-fastapi-instrumentator==7.0.0
      - prompt-toolkit==3.0.47
      - protobuf==5.27.3
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pyairports==2.1.1
      - pycountry==24.6.1
      - pydantic==2.8.2
      - pydantic-core==2.20.1
      - pygments==2.18.0
      - python-dotenv==1.0.1
      - pyzmq==26.1.0
      - ray==2.34.0
      - referencing==0.35.1
      - rpds-py==0.19.1
      - scipy==1.14.0
      - sentencepiece==0.2.0
      - sniffio==1.3.1
      - soupsieve==2.6
      - stack-data==0.6.3
      - starlette==0.37.2
      - tiktoken==0.6.0
      - tinycss2==1.3.0
      - torch==2.4.0
      - torchvision==0.19.0
      - tornado==6.4.1
      - traitlets==5.14.3
      - transformers==4.44.0
      - triton==3.0.0
      - uvicorn==0.30.5
      - uvloop==0.19.0
      - vllm==0.5.4
      - vllm-flash-attn==2.6.1
      - vllm-nccl-cu12==2.18.1.0.4.0
      - watchfiles==0.22.0
      - wcwidth==0.2.13
      - webencodings==0.5.1
      - websockets==12.0
      - xformers==0.0.27.post2
      - yarg==0.1.9
prefix: /root/anaconda3/envs/coe
